/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import controlador.Reportes;

/**
 *
 * @author Jean
 */
public class FrmReportes extends javax.swing.JPanel {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btn_reporte_cliente = new javax.swing.JButton();
        btn_reporte_categorias = new javax.swing.JButton();
        btn_reporte_ventas = new javax.swing.JButton();
        btn_reporte_productos = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_reporte_cliente.setBackground(new java.awt.Color(0, 0, 0));
        btn_reporte_cliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reporte_cliente.setText("GENERAR REPORTE DE CLIENTES");
        btn_reporte_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reporte_cliente.setContentAreaFilled(false);
        btn_reporte_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reporte_cliente.setFocusPainted(false);
        btn_reporte_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_clienteActionPerformed(evt);
            }
        });

        btn_reporte_categorias.setBackground(new java.awt.Color(0, 0, 0));
        btn_reporte_categorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reporte_categorias.setText("GENERAR REPORTE DE CATEGORIAS");
        btn_reporte_categorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reporte_categorias.setContentAreaFilled(false);
        btn_reporte_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reporte_categorias.setFocusPainted(false);
        btn_reporte_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_categoriasActionPerformed(evt);
            }
        });

        btn_reporte_ventas.setBackground(new java.awt.Color(0, 0, 0));
        btn_reporte_ventas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reporte_ventas.setText("GENERAR REPORTE DE VENTAS");
        btn_reporte_ventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reporte_ventas.setContentAreaFilled(false);
        btn_reporte_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reporte_ventas.setFocusPainted(false);
        btn_reporte_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_ventasActionPerformed(evt);
            }
        });

        btn_reporte_productos.setBackground(new java.awt.Color(0, 0, 0));
        btn_reporte_productos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reporte_productos.setText("GENERAR REPORTE DE PRODUCTOS");
        btn_reporte_productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reporte_productos.setContentAreaFilled(false);
        btn_reporte_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reporte_productos.setFocusPainted(false);
        btn_reporte_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_productosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reporte_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_reporte_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_reporte_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_reporte_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_reporte_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reporte_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_clienteActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReporteClientes();
    }//GEN-LAST:event_btn_reporte_clienteActionPerformed

    private void btn_reporte_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_categoriasActionPerformed
        // TODO add your handling code here:
        Reportes reporte = new Reportes();
        reporte.ReportesCategorias();
    }//GEN-LAST:event_btn_reporte_categoriasActionPerformed

    private void btn_reporte_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_ventasActionPerformed
        // TODO add your handling code here:
        Reportes reporte = new Reportes();
        reporte.ReportesVentas();
    }//GEN-LAST:event_btn_reporte_ventasActionPerformed

    private void btn_reporte_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_productosActionPerformed
        // TODO add your handling code here:
        Reportes reporte = new Reportes();
        reporte.ReportesProductos();
    }//GEN-LAST:event_btn_reporte_productosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btn_reporte_categorias;
    private javax.swing.JButton btn_reporte_cliente;
    private javax.swing.JButton btn_reporte_productos;
    private javax.swing.JButton btn_reporte_ventas;
    // End of variables declaration//GEN-END:variables
}
